### ISSUE TITLE
Access tuner Issue / confirmation issue

### ISSUE THREAD

**Issue by backstaia** [Nibre/MotherVR#140]
I love this game and mod to death and with the new version its incredible. The only issue I am facing is the confirmation button. When using the accesstuner it works perfectly fine to tune the and select the code but since selecting an item in menu down and confirm on the right vive wand is the same button I can select the code in the upper bar but when I want to confirm it with touchpad down touch jumps to the row down and confirms the wrong code. It is super annoying and stressful Its the same issue when using the in game menu. Is there any work around or am I doing something wrong? Thanks for you hard work nibre!

**Comment by ElricOfMelnibone** [comment]
Happens to me too. I've found that tapping the touchpad carefully in the direction I want, instead of sliding my finger, helps avoid this problem a lot.

EDIT: scrap that advice. Use the left touchpad to select the code piece, use the right *grip* to confirm each piece.

The toughest thing is getting past the 3 terminals for the comms mission to contact the Torrnens. The voltage balancer responds to nothing, the 3 vertical boxes with codes that you need to hit a corresponding control for will only work for the bottom 2 (I could not find a way to get the top code to lock), and the only puzzle that works is the 4-column scrolling codes that you just hit right touchpad down to select when they're highlighted. Since the puzzles come up randomly, you can back out of the first terminal and back in again to get the 4-column, but on the second & third terminals if you back out, you start from terminal 1 again, so you have to wait for each to time out unless/until you get the 4-column puzzle.

**Comment by backstaia** [comment]
Solved. I found the release post of nibre on reddit with a hint. You can use left touchpad click to confirm in access tuner menu. After getting used to it works quite well.

**Comment by ElricOfMelnibone** [comment]
I think I'll stick with using the right grip to confirm. Any time I try to do a left touchpad down _click_ to confirm, it moves my selection when my thumb touches the pad. I can avoid that problem entirely using the right grip. But whatever works best for you.

**Comment by backstaia** [comment]
I just saw your edit. You can really use the right grip to confirm? That seems perfect. I thought I have tried all buttons. I need to verify this, if it really works that would be perfect. Do you by chance know how to reload batteries for the headlamp? Since I have run out of juice I have found no way to reload them. Makes vents beyond scary ;-) Also do you know how to holster stuff. I seem to be unable to to put flares/gadgets away. Thanks for the advice!

**Comment by ElricOfMelnibone** [comment]
Yeah the right-grip confirm definitely works for me, I think you'll like it.
For the headlamp, use the same control (right touchpad down) you click for activating the lamp, but instead of a single click, hold it down while your controller is near your head until you hear a sound of the fresh batteries being popped into the flashlight.
I haven't really figured out holstering either. What I do instead is switch to the revolver or the baton, which automatically drop out of sight. Seeing my noisemakers, etc, constantly in front of me was distracting.   ;)
Now I just need to figure out how to hold my breath in lockers properly. Seems like no matter what I do, the alien finds me, despite trying the left trigger, though I did once see an instruction for touching left touchpad down, so maybe I did something right and that was the follow-up? But I was too slow and got head-chomped anyway, lol
