### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by charbouzo** [Nibre/MotherVR#74]
Is this project still going? It has been several months with no feedback from the developer. Hope all is well.
Thanks.

**Comment by Nibre** [comment]
Yes, this is still being worked on

**Comment by charbouzo** [comment]
Thanks Nibre and its an excellent job what you have done so far.

**Comment by matt90410** [comment]
Yes, thanks Nibre for all your work.  It is such an amazing experience in VR!  In a previous release you mentioned that snap turning was nearly finished.  I am just wondering whether that is something that can be released soon?  I struggle with anything more than 30 mins due to turning, and snap turning would make a big difference to me.  Ideally a few settings e.g. 45, 90, 180 degrees etc.

**Comment by cercata** [comment]
Happy this is still alive !!!!

If you stop it, I think is playable now, and I'll play it.
But if you are working on it, I'll wait until it's finished :)

**Comment by greensouth** [comment]
So great!! tried again after my first test several months ago, and damn, it's the most terrifying game on VR ever!

So bad I still get nausea because of the movement. Can't wait for the snap turn! :)

Great work! We hope to hear news soon.

**Comment by Nibre** [comment]
I'm going to go ahead and close this.. because of the new [Release](https://github.com/Nibre/MotherVR/releases)!
